import React from 'react';
import ExampleWorkBubble from './example-work-bubble'

class ExampleWork extends React.Component {
  render() {
    return (
      <section className="section section--alignCentered section--description">

        {
            this.props.work.map ((example, idx) => {
              return (
                    <ExampleWorkBubble example={example} key={idx} />
                )
            })
        }


    {/*  <div className="section__exampleWrapper">
          <div className="section__example">
            <img alt="example screenshot of a project involving cats"
                 className="section__exampleImage"
                 src="images/myVacationProperty.jpeg"/> */}
            {/* “Bengal cat” by roberto shabs is licensed under CC BY 2.0
                 https://www.flickr.com/photos/37287295@N00/2540855181 */}


        {/*}    <dl className="color--cloud">
              <dt className="section__exampleTitle section__text--centered">
                Zoom
              </dt>
              <dd></dd>
            </dl>
          </div>
        </div> */}

        {/*
          Notes - instead of having static markup, it's generated by react based on data
          benefits:  (1) easier to keep markup consistent (2) only change in one place (3) easier to test portfolio
           */}

      </section>
    )
  }
}

export default ExampleWork
