import React from 'react';
import ExampleWorkBubble from './example-work-bubble'
import ExampleWorkModal from './example-work-modal'

class ExampleWork extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      'modalOpen': false,
      'selectedExample': this.props.work[0]
    };

    this.openModal = this.openModal.bind(this);
    this.closeModal = this.closeModal.bind(this);
  }

  openModal(evt, example) {
    this.setState({
      'modalOpen': true,
      'selectedExample': example
    })
  }

  closeModal(evt) {
    this.setState({
      'modalOpen': false
    });
  }

  render() {
    return (
      <span>
      <section className="section section--alignCentered section--description">

        {
            this.props.work.map ((example, idx) => {
              return (
                    <ExampleWorkBubble example={example} key={idx}
                      openModal={this.openModal}/>
                )
            })
        }


    {/*  <div className="section__exampleWrapper">
          <div className="section__example">
            <img alt="example screenshot of a project involving cats"
                 className="section__exampleImage"
                 src="images/myVacationProperty.jpeg"/> */}
            {/* “Bengal cat” by roberto shabs is licensed under CC BY 2.0
                 https://www.flickr.com/photos/37287295@N00/2540855181 */}


        {/*}    <dl className="color--cloud">
              <dt className="section__exampleTitle section__text--centered">
                Zoom
              </dt>
              <dd></dd>
            </dl>
          </div>
        </div> */}

        {/*
          Notes - instead of having static markup, it's generated by react based on data
          benefits:  (1) easier to keep markup consistent (2) only change in one place (3) easier to test portfolio
           */}

      </section>

      <ExampleWorkModal example={this.state.selectedExample}
        open={this.state.modalOpen} closeModal={this.closeModal}/>
      </span>
    )
  }
}

export default ExampleWork
