version: 0.1

phases:
  pre_build:
      commands:
          - npm install
          - npm test
  build:
      commands:
          - npm run webpack ## HERE?
artifacts:
    files:
        - index.html
        - favicon.ico
        - RobinNorwood-Resume.pdf
        - styles/main.css
        - images/*
        - dist/* #TOLD CODEBUILD WHAT TO DO

            # tried fixing by changing dist and specifying bundle.js
